### ISSUE TITLE
Can you make it smoother for Android?

### ISSUE THREAD

**Issue by brooklyn097** [torgeadelin/react-native-animated-nav-tab-bar#1]
I've checked out this for both iOS and Android and it's working perfectly on iOS but on Android it's lagging on every touch to tab button.
Could you fix this?

**Comment by torgeadelin** [comment]
Hi @brooklyn097 , I will try to have a look at it as soon as I can. Thanks for reporting the unusual behavior on Android.  Please tell me what device did you test on, and what Android SDK.

**Comment by brooklyn097** [comment]
I forgot to update to this thread. It was lagging only with development mode, I've tried with a release apk and it works as expected.
Thank you!

**Comment by torgeadelin** [comment]
Thanks for letting me know.

**Comment by itajenglish** [comment]
I'm experiencing the same issue when the debugger is on for Android. Any idea what may be causing this?
