### ISSUE TITLE
Possible Typescript support??

### ISSUE THREAD

**Issue by kockok** [torgeadelin/react-native-animated-nav-tab-bar#10]
`Could not find a declaration file for module 'react-native-animated-nav-tab-bar'. `

**Comment by giangidev93** [comment]
same here

**Comment by ghost** [comment]
This would be amazing to be support on TypeScript! What a great nav bar!

**Comment by torgeadelin** [comment]
I'll try to do this soon. I'm happy to see more and more interest in this package. Thanks!

**Comment by ayell** [comment]
It's a great package and it will be better when TS will be support  :)

**Comment by torgeadelin** [comment]
Currently working on this.

**Comment by torgeadelin** [comment]
Long-awaited typescript support is now out :)
