### ISSUE TITLE
How to hide labels?

### ISSUE THREAD

**Issue by nimblemo** [torgeadelin/react-native-animated-nav-tab-bar#100]
How to hide labels?

this react-navigation solutions wont work to me

```js
tabBarOptions={ {
        showLabels: false
     } }
```

```jsx
<Tab.Screen options={ { showLabel: false } } name="wallet" component={ WalletStack } />
```

**Comment by torgeadelin** [comment]
If you look at the documentation in the README you can find `whenActiveShow`and `whenInactiveShow` props what can help you customise that.
