### ISSUE TITLE
Not compatible with react-navigation v6

### ISSUE THREAD

**Issue by eliasljubec** [torgeadelin/react-native-animated-nav-tab-bar#105]
I tried to upgrade from react-navigation v5 to v6, unfortunately it did not work because of this error

> Error: Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'?

And yes, I wrapped NavigationContainer (see screenshot), **it worked wonderfully with the v5** version but unfortunately not with v6. Is this a known issue when upgrading to v6? I have tried clearing my yarn cache and reinstalling my node modules folder.

![image](https://user-images.githubusercontent.com/36228716/134916026-1d586e8b-d159-467f-ab9f-648f163f7ec6.png)

**Comment by rogeraugusto** [comment]
@eljubec if you remove react-navigation/native from your **dependencies** and put it on **peerDependencies**, as commented below, you can install v6.  I tryed and it worked. However, I recommend v5, as is in the lib documentation, to the best performance.

```
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-animated-nav-tab-bar": "^3.1.4",
    "react-native-screens": "^3.8.0",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.2.2",
    "styled-components": "^5.3.1"
  },
  "peerDependencies": {
    "@react-navigation/native": "^6.0.4"
  },
```

**Comment by sidsarasvati** [comment]
any idea when we can have support for v6? 
happy to help if any one can put info of development work in progress

**Comment by cmcodes1** [comment]
> @eljubec if you remove react-navigation/native from your **dependencies** and put it on **peerDependencies**, as commented below, you can install v6. I tryed and it worked. However, I recommend v5, as is in the lib documentation, to the best performance.
> 
> ```
>   "dependencies": {
>     "@react-native-community/masked-view": "^0.1.11",
>     "react": "17.0.2",
>     "react-native": "0.65.1",
>     "react-native-animated-nav-tab-bar": "^3.1.4",
>     "react-native-screens": "^3.8.0",
>     "react-native-safe-area-context": "^3.3.2",
>     "react-native-gesture-handler": "^1.10.3",
>     "react-native-reanimated": "^2.2.2",
>     "styled-components": "^5.3.1"
>   },
>   "peerDependencies": {
>     "@react-navigation/native": "^6.0.4"
>   },
> ```

Tried this! Still facing the same issue!

**Comment by jamesjara** [comment]
I'm having the same issue

**Comment by NooruddinLakhani** [comment]
Facing the same issue. Any work around?
