### ISSUE TITLE
Tab bar goes up with the keyboard

### ISSUE THREAD

**Issue by igorcesarcode** [torgeadelin/react-native-animated-nav-tab-bar#107]
Sorry my english i'm not native.

Tab bar goes up with the keyboard when I click on a TextInput dp field

![image](https://user-images.githubusercontent.com/44711552/143626636-6e77ac07-21c1-41ca-977f-2462d947017e.png)

How to get around this?

**Comment by torgeadelin** [comment]
Hi, I think this is default behaviour, could you try this https://github.com/react-navigation/react-navigation/issues/6700#issuecomment-546794842 ?

**Comment by oussamalahrizi** [comment]
same problem , I think it's not am option in the current package they'll have to add the necessary property for it . Any news tho ?

**Comment by rahmanharoon** [comment]
Same problem @torgeadelin tried that and didn't fixed

**Comment by vagnerlandio** [comment]
Solved my problem with this https://github.com/react-navigation/react-navigation/issues/6700#issuecomment-834263561

**Comment by torgeadelin** [comment]
Not sure this is related to this library, so closing for now.
