### ISSUE TITLE
The library needs to move @react-navigation/native to peerDependencies.

### ISSUE THREAD

**Issue by khelifioussama** [torgeadelin/react-native-animated-nav-tab-bar#109]
This is a problem in the react-native-animated-nav-tab-bar package. It adds @react-navigation/native to its dependencies which makes it possible to include multiple versions of @react-navigation/native since you will also have it in your own package.json, and multiple versions of @react-navigation/native will cause such issues:

https://github.com/torgeadelin/react-native-animated-nav-tab-bar/blob/0642630cb487a496b0619201daa68cdd164f8f14/package.json#L59

The library needs to move @react-navigation/native to peerDependencies.

It also does the same for react-native-screens, it's in dependencies whereas it should be in peerDependencies.

**Comment by torgeadelin** [comment]
Please update to the latest version, this should be fixed now.
