### ISSUE TITLE
error: Error: While trying to resolve module `react-native-animated-nav-tab-bar` from file 

### ISSUE THREAD

**Issue by Batsirai-sudo** [torgeadelin/react-native-animated-nav-tab-bar#110]
error: Error: While trying to resolve module `react-native-animated-nav-tab-bar` from file `/Users/mac/{**My path to index**}/index.tsx`, the package `/Users/mac/{**My path to node_modules**}/node_modules/react-native-animated-nav-tab-bar/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/mac/{**My path to node_modules**}/node_modules/react-native-animated-nav-tab-bar/dist/lib/index.js`. Indeed, none of these files exist:

**Comment by ShubhamJain0** [comment]
Are you using react-navigation v6 too?

**Comment by BloodDSHOT** [comment]
I'm also getting same error,
"react-navigation": "^4.3.7"

**Comment by hpelitebook745G2** [comment]
i think there's really a dependency issue with this lib, a react navigation developer had something to say it [here](https://stackoverflow.com/a/68783352/1968739)

**Comment by milos201** [comment]
That's because when the module is installed, `./node_modules/react-native-animated-nav-tab-bar/` only has three files: `package.json`, `LICENSE` and `README.md`.

**Comment by torgeadelin** [comment]
This issue has been fixed in 3.1.7, please upgrade :)
