### ISSUE TITLE
Add ref to react-native-animated-nav-tab-bar

### ISSUE THREAD

**Issue by kockok** [torgeadelin/react-native-animated-nav-tab-bar#119]
As I set the tab bar to `float` in ios and not for android, and I need the position of pageX and PageY to put items just above the tab bar.

So, please also export the position of react-native-animated-nav-tab-bar.

**Comment by kkkasio** [comment]
> As I set the tab bar to `float` in ios and not for android, and I need the position of pageX and PageY to put items just above the tab bar.
> 
> So, please also export the position of react-native-animated-nav-tab-bar.

hi! hou solved this question? when i have scrollview in content page, my tab bar stays on top 

<img width="382" alt="Screenshot 2023-09-20 at 23 01 55" src="https://github.com/torgeadelin/react-native-animated-nav-tab-bar/assets/19254402/87114296-8531-4e70-af94-f5556e15889d">
