### ISSUE TITLE
How to change the default active tab when the app opens ?

### ISSUE THREAD

**Issue by surbhitrao** [torgeadelin/react-native-animated-nav-tab-bar#12]
How to change the default active tab when the example app opens ?  It is set to default to the left most item.

**Comment by torgeadelin** [comment]
I think this is a matter of React Navigation rather that this package. The highlight of the selected tab corresponds to the state of your navigation state. Try change that maybe?
Maybe [this](https://stackoverflow.com/questions/55570886/how-to-set-a-default-screen-route-in-react-tab-navigation-in-react-native) helps.
