### ISSUE TITLE
Missing bottom padding/margin on iPhone 14 pro

### ISSUE THREAD

**Issue by marcus-chr** [torgeadelin/react-native-animated-nav-tab-bar#123]
Missing bottom padding/margin between the tabs and the "black horizontal line".

Screenshot from a iPhone 14 Pro Max. Works great on e.g. iPhone 12 Pro Max.

![201533362-a84412ba-af16-4ca4-a44c-983621dc3c69](https://user-images.githubusercontent.com/12811831/202518934-908a340f-fb4f-423a-b750-0fa04f92897f.png)

**Comment by programmrz** [comment]
same issue here, but on the pro max. somehow floating has it.

**Comment by programmrz** [comment]
okay, I solved the issue. It uses (isIphonex), which literally checks the notch by checking if it's an ios platform and then checking a hard coded list of Dimensions.get('window').height. You can A) add the iPhone 14 pro & Max heights or B) go ahead an import react-native-safe-area-context and get useSafeAreaInsets and add it to the config. I don't know how to use git and do a pull request?

**Comment by brunowilliang** [comment]
@programmrz, @marcus-chr  hey guys, did you solve this problem?

**Comment by programmrz** [comment]
@Brunowilliang I did, but ended up no longer using the package. 

Go into node_modules/react-native-animated-nav-tab-bar/dist/lib/index.js

On line 156, add your iPhone's screen dimension to the list.

**Comment by brunowilliang** [comment]
@programmrz like this? Can you show me where I should move and what to put?
![Screenshot 2023-03-21 at 09 14 42](https://user-images.githubusercontent.com/41432581/226602815-8b4b67dd-2a37-402f-9ef3-a2ad48b603a4.png)

**Comment by programmrz** [comment]
@Brunowilliang 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/8770307/226604837-edbe028f-1187-407c-9cb0-0ee121866714.png">
I would suggest using an alternate package, any time you run npm install or anything else, it'll reset and you'll need to do this again.

**Comment by brunowilliang** [comment]
@programmrz I think it's because of this lib
https://github.com/ptelad/react-native-iphone-x-helper
is no longer receiving updates, would need to switch to another lib :(

**Comment by muhammedesadkaya** [comment]
@programmrz is there any alternative lib? I really can't find for RN-navigation v6

**Comment by fukemy** [comment]
please update the lib, this is very noisy in iPhone 14

**Comment by torgeadelin** [comment]
This should work on latest release. 3.1.10
