### ISSUE TITLE
Support for React 18 (Expo 47)

### ISSUE THREAD

**Issue by aaron5670** [torgeadelin/react-native-animated-nav-tab-bar#124]
**Describe the bug**
Can't install [react-native-animated-nav-tab-bar](https://github.com/torgeadelin/react-native-animated-nav-tab-bar) with the latest React version.

**To Reproduce**
1. Create a new React Native app with Expo 47+.
2. Run ``npm install react-native-animated-nav-tab-bar``

**Screenshots**
<img width="917" alt="image" src="https://user-images.githubusercontent.com/17295145/205140284-8939b56c-a59b-487e-996a-a4e00ea06f6a.png">

**Comment by itajenglish** [comment]
@aaron5670 It is working for me with the latest SDKs. Be sure to install the `styled-components` package as well.

**Comment by aaron5670** [comment]
@itajenglish thanks! I''ll try again tonight. 😀
