### ISSUE TITLE
error: Error: Unable to resolve module styled-components/native

### ISSUE THREAD

**Issue by devamitch** [torgeadelin/react-native-animated-nav-tab-bar#125]
styled-components/native could not be found within the project or in these directories:
  node_modules
  ../../../../node_modules
   7 | var reactNative = require('react-native');
   8 | var reactNativeScreens = require('react-native-screens');
>  9 | var Styled = require('styled-components/native');
     |                       ^
  10 |
  11 | function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
  12 |
    at ModuleResolver.resolveDependency

**Comment by lunacer** [comment]
FYI, I just manually added styled-components to my project and could resolve the error.

**Comment by hainm149889** [comment]
any answer??

**Comment by gesangseto** [comment]
Just install styled-components
```npm install styled-components```

**Comment by torgeadelin** [comment]
This should work on latest release. 3.1.10
Styled components is now a requirement.
