### ISSUE TITLE
The position of the pressed tab does not match the result

### ISSUE THREAD

**Issue by gesangseto** [torgeadelin/react-native-animated-nav-tab-bar#127]
I do not understand this can happen? Is there something wrong with the dependencies?

![ezgif-4-516cdd7e8b](https://github.com/torgeadelin/react-native-animated-nav-tab-bar/assets/49031964/65688142-8ebf-4ac1-b6dd-f0882f8d4532)

```
 "dependencies": {
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-animated-nav-tab-bar": "^3.1.8",
    "react-native-gesture-handler": "^1.10.3",
  },
```

**Comment by torgeadelin** [comment]
Please provide a sandbox with reproducible code, I can't debug by just looking at the gif.

**Comment by torgeadelin** [comment]
But my first thought is that your tab component is not implemented properly.
