### ISSUE TITLE
Icons are moving (shifting few pixels) on each transition

### ISSUE THREAD

**Issue by joksa** [torgeadelin/react-native-animated-nav-tab-bar#128]
The component works great just annoying sliding (moving) icons on each transition (especially the first and the last).
I tried with padding and margin but didn't help.

**Comment by torgeadelin** [comment]
Please provide code so I can reproduce, or a gif. Although I _think_ I know what you mean... I don't love that they shift either... If you figure out a way to fix this, please raise a PR.

**Comment by joksa** [comment]
> Please provide code so I can reproduce, or a gif. Although I _think_ I know what you mean... I don't love that they shift either... If you figure out a way to fix this, please raise a PR.

You can see it on the Animation Preview you posted on the GitHub page it is exactly the same. If you go from third or forth icon to first or second there is a shift of icons few pixels but noticeable.
