### ISSUE TITLE
Tabbar hide on opens keyoborad is not working as expected

### ISSUE THREAD

**Issue by jaxkashif34** [torgeadelin/react-native-animated-nav-tab-bar#133]
When set the option `tabBarHideOnKeyboard : false`  it is not working as expected. like it does works in [react-native-navigation](https://reactnavigation.org/docs/bottom-tab-navigator/#tabbarhideonkeyboard)

![keyboard-issue](https://github.com/torgeadelin/react-native-animated-nav-tab-bar/assets/28916829/ccaf36fa-22da-4dc5-8821-fc6466f160df)

**I setted the `tabBarHideOnKeyboard : false`**

![hide keyboard option](https://github.com/torgeadelin/react-native-animated-nav-tab-bar/assets/28916829/2885da64-980f-4d0b-bfc1-740825c6d2f4)

**Comment by parulgarg004** [comment]
Facing the same issue, can you please help @torgeadelin

**Comment by jaxkashif34** [comment]
> Facing the same issue, can you please help @torgeadelin

No I haven't find any solution of it but I think I have to chose another npm package or might need to alter the library to achieve it

**Comment by parulgarg004** [comment]
> > Facing the same issue, can you please help @torgeadelin
> 
> No I haven't find any solution of it but I think I have to chose another npm package or might need to alter the library to achieve it

Let me know if you fix it.

**Comment by jaxkashif34** [comment]
> > > Facing the same issue, can you please help @torgeadelin
> > 
> > 
> > No I haven't find any solution of it but I think I have to chose another npm package or might need to alter the library to achieve it
> 
> Let me know if you fix it.

Sure

**Comment by hdwts** [comment]
Facing same issue any fix ?
