### ISSUE TITLE
Is it possible to make the bar's top corners rounded?

### ISSUE THREAD

**Issue by speter9701** [torgeadelin/react-native-animated-nav-tab-bar#21]
I've tried to add borderRadius to the tabBarOptions, but it does not working. 
Is there any possible way to do that?

**Comment by torgeadelin** [comment]
Currently there is no way you can customise that. I will add a prop to make it easier to customise the appearance (including round corners). I’ll try to push a new version this coming week. Thanks for the feedback!

**Comment by torgeadelin** [comment]
Fixed. See #23

**Comment by ferostabio** [comment]
Hi there! Sorry @torgeadelin , but just went through the code and I an't find a reference to the bar's top radius. Only the dot's, with the `dotCornerRadius` prop.

**Comment by torgeadelin** [comment]
@ferostar to change the actual tab bar style use the `tabBarOption` prop and add your style to the tabStyle property.
```
tabBarOptions={{
    tabStyle: {
        borderRadius: 10,
    },
}}

```

**Comment by iusama46** [comment]
> @ferostar to change the actual tab bar style use the `tabBarOption` prop and add your style to the tabStyle property.
> 
> ```
> tabBarOptions={{
>     tabStyle: {
>         borderRadius: 10,
>     },
> }}
> ```

Tried this one is not working right now

**Comment by iusama46** [comment]
Fixed by using

appearance={{ floating: false , dotCornerRadius:10}}
