### ISSUE TITLE
Navbar breaks on changing orientation

### ISSUE THREAD

**Issue by nirmaldalmia** [torgeadelin/react-native-animated-nav-tab-bar#22]
I've implemented the bottom nav tab bar for four tabs. It breaks and highlights the wrong part whenever we switch the orientation from portrait to landscape or vice versa. Here are the screenshots:

1. Navbar fine in portrait mode
![image](https://user-images.githubusercontent.com/27962178/85234858-25915c00-b42e-11ea-8ca3-1130f2ee4bc0.png)

    Upon changing orientation to landscape
    ![image](https://user-images.githubusercontent.com/27962178/85234864-39d55900-b42e-11ea-802a-16f13a220a29.png)
<br>

2. Navbar fine in landscape mode
![image](https://user-images.githubusercontent.com/27962178/85234867-45288480-b42e-11ea-9984-619d8daf830a.png)

    Upon changing orientation to portrait
    ![image](https://user-images.githubusercontent.com/27962178/85234873-507bb000-b42e-11ea-91cc-4c862ab23539.png)

I really like this navbar and hope to see a resolution for the issue.

**Comment by torgeadelin** [comment]
Hi! Thanks for raising the issue. I will look into it and try to push a fix this coming week.

**Comment by torgeadelin** [comment]
Hi, are you running on iOS or Android? 
Thanks!

**Comment by nirmaldalmia** [comment]
Hi! I tested it on Android. Not sure about IOS.

**Comment by torgeadelin** [comment]
No worries, I'll push a fix in a few hours. I already fixed the issue but I'm adding some additional features, and doing some refactoring. I'd be great if you can confirm the issue is fixed on Android once I push the fix. (I don't currently have Android)

**Comment by nirmaldalmia** [comment]
Sure. I'd be happy to help out. So happy to see such a quick resolution! Thanks!

**Comment by torgeadelin** [comment]
Hi @nirmaldalmia, sorry for the delay. I just pushed a new version, v3.0.1, please update the package in your project, and check if the orientation change issue is fixed. Also, make sure to reimplement the navigation using the new style (see docs).
Thanks!

**Comment by nirmaldalmia** [comment]
Hey @torgeadelin thanks for the update. I Will test and let you know how it works out!

**Comment by nirmaldalmia** [comment]
Hey sorry for the delay in responding. Thanks for the fix! It works great :)
