### ISSUE TITLE
Error - Can't find variable: HandleBackPress

### ISSUE THREAD

**Issue by saihtunlu** [torgeadelin/react-native-animated-nav-tab-bar#24]
Hi Bro, i'm facing this error - Can't find variable: HandleBackPress, and it's fixed by adding 'const' (at TabBarElement.js: 115). 
` const handleBackPress = () => {
    animation(animatedPos).start(() => {
      updatePrevPos();
    });
  };`

**Comment by renzified** [comment]
+1  here

**Comment by torgeadelin** [comment]
Fixed! Please update to 3.0.2 :)
