### ISSUE TITLE
fontFamily not taking effect in labelStyle property of tabBarOptions

### ISSUE THREAD

**Issue by renzified** [torgeadelin/react-native-animated-nav-tab-bar#26]
I want to change the fontFamily of the tab label to match my entire app. Unfortunately its not taking effect.
Here is my tabBarOptions

```
{
       activeTintColor: 'white',  
       inactiveTintColor: 'gainsboro',  
       activeBackgroundColor: 'purple',  
       labelStyle: {  
                   fontFamily: 'Montserrat-Regular',  
                   color: 'white'  
       }  
 }
```

**Comment by torgeadelin** [comment]
Hi!

Does the colour change according to what you specify in the `labelStyle`?

**Comment by renzified** [comment]
> Hi!
> 
> Does the colour change according to what you specify in the `labelStyle`?

Yes it does change

**Comment by renzified** [comment]
Found the solution i removed this line
https://github.com/torgeadelin/react-native-animated-nav-tab-bar/blob/d1d41be93637b17d0c9036488078c8bb231b0ee5/src/UIComponents.js#L74
and used the bold fontFamily Montserrat-Bold Like so
```
{
       activeTintColor: 'white',  
       inactiveTintColor: 'gainsboro',  
       activeBackgroundColor: 'purple',  
       labelStyle: {  
                   fontFamily: 'Montserrat-Bold',  
                   color: 'white'  
       }  
 }
```
