### ISSUE TITLE
TabBar indicator position keeps standing when using navigation.navigate()

### ISSUE THREAD

**Issue by brooklyn097** [torgeadelin/react-native-animated-nav-tab-bar#3]
Hi, I'm fresher with React Native so if you can give me an advice for my problem it would be more than great.
For example, suppose I've 2 screens called A and B, both of them are inside a TabBar, i can switch between screen A and screen B by clicking on TabBar for normally but in my situation i want to navigate to screen B when i press to a button on screen A. I'm currently using `this.props.navigation.navigate('screenB')`
and it does switches to screen B but the animation on TabBar doesn't work, it gets stuck at the position of screen A.

**Comment by torgeadelin** [comment]
Hi! I am new with React Native as well haha, I have a rough idea why it’s not working. I’ll try to fix it in the next few days and I’ll let you know. Thanks for reporting the unusual behaviour.

**Comment by brooklyn097** [comment]
Seems you’re too busy haha, can you share your idea on the issue so i can have a look into this.

**Comment by torgeadelin** [comment]
Hi. Yes, I apologise. I’m on holiday right now.
I think I have a quick fix for you. Have a look at this https://reactnavigation.org/docs/en/function-after-focusing-screen.html and then try to get a reference from the TabBar component and pass it to your screen. And whenever you go to that screen you trigger the onPress function. Not entirely sure it’s gonna work.

Hope this helps.
Thanks!

**Comment by brooklyn097** [comment]
Hi, I'll try following your idea and give you feedback soon. Thank you!

**Comment by saraf22** [comment]
adding this in Tabbar.js does the fix @torgeadelin 

componentDidUpdate(prevProps) {
if(prevProps.navigation.state.index !== this.props.navigation.state.index) {
    this.animation(this.state.animatedPos).start(() => {
        this.setState({
          prevPos: this.state.pos,
        });
        this.state.animatedPos.setValue(0);
      });
}
}

**Comment by damithg-dev** [comment]
@saraf22 thank you mate. working charm. please make PR.

**Comment by torgeadelin** [comment]
This is finally fixed! #18

**Comment by torgeadelin** [comment]
Fixed!
