### ISSUE TITLE
Seems incompatible with ui-kitten eva-icons

### ISSUE THREAD

**Issue by kockok** [torgeadelin/react-native-animated-nav-tab-bar#30]
I followed the [example](https://github.com/torgeadelin/react-native-animated-nav-tab-bar/blob/master/example/navigation/AppNavigation.js)  js to get started, however, an error raised likely related to the Icon rendering:
```
[Sun Jul 26 2020 23:54:46.387]  ERROR    Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Icon`.
```

The official docs written like this:
```
import React from 'react';
import { Button, Icon } from '@ui-kitten/components';

const FacebookIcon = (props) => (
  <Icon name='facebook' {...props} />
);

export const LoginButton = () => (
  <Button accessoryLeft={FacebookIcon}>Login with Facebook</Button>
);
```
And I can't see what went wrong.

Please advise.

**Comment by torgeadelin** [comment]
Hey! It seems like it's an issue with the your i on library not the navigation component. Make sure you import your icons according to the library you're using.

**Comment by kockok** [comment]
> Hey! It seems like it's an issue with the your i on library not the navigation component. Make sure you import your icons according to the library you're using.

Even I dismiss the `Check the render method of `Icon`.` error, however, the icon won't show up. And the styling went crazy.
![Screenshot 2020-07-27 at 4 35 09 PM](https://user-images.githubusercontent.com/232541/88521248-3e8dbe00-d027-11ea-9761-a8e9b346f2c4.png)

I guess that ui kitten icons are rendering jsx elements and the `tabBarIcon` option only respond to svg icons.

**Comment by torgeadelin** [comment]
Could you post your whole navigation code?

**Comment by kockok** [comment]
@torgeadelin The problem is solved, and I think it's the problem of the Icon library setting.
1, you have to provide width and height value to avoid collapsing the styling.
2, the name value of the icon is important, e.g.`<Icon name="profile">`, we don't have "profile" in eva icons, so the `Check the render method of Icon.`  error is being raised.

Hope this will help.
