### ISSUE TITLE
Invariant Violation: Invalid prop `backgroundColor` supplied to `StyleSheet generated`

### ISSUE THREAD

**Issue by maheshlipane99** [torgeadelin/react-native-animated-nav-tab-bar#34]
**Invariant Violation: Invalid prop `backgroundColor` supplied to `StyleSheet generated`:**
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

StyleSheet generated: {
  "position": "absolute",
  "top": 20,
  "width": 0,
  "height": 0,
  "borderRadius": 100,
  "backgroundColor": "",
  "zIndex": -1
}

    <Tabs.Navigator
      tabBarOptions={{
        activeTintColor: "#2F7C6E",
        inactiveTintColor: "#222222",
      }}
 
    >
      <Tabs.Screen name="Home" component={HomeScreen} />
      <Tabs.Screen name="Orders" component={Orders} />
      <Tabs.Screen name="Profile" component={Profile} />
    </Tabs.Navigator>

**Comment by torgeadelin** [comment]
Hi, what was the issue?

**Comment by FawadMahmood** [comment]
Having same issue.

**Comment by Mimicx** [comment]
Same issue..

**Comment by Mimicx** [comment]
i noticed that adding the prop activeBackgroundColor, the error disappear.
