### ISSUE TITLE
Invariant Violation: Invalid prop `backgroundColor` supplied to `StyleSheet generated`: 

### ISSUE THREAD

**Issue by secodigo** [torgeadelin/react-native-animated-nav-tab-bar#35]
I created the example and the following error occurs to me:
Invalid prop `backgroundColor` supplied to `StyleSheet generated`: 
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

StyleSheet generated: {
  "position": "absolute",
  "top": 20,
  "width": 0,
  "height": 0,
  "borderRadius": 100,
  "backgroundColor": "",
  "zIndex": -1
}

**Comment by mstf0ta-app** [comment]
I solve it by editing UIComponents.js
line 73  color: ${(p) => p.activeColor} to hex color:"#000" or any color you want
line 84 background-color: ${(p) => p.activeTabBackground}; to  background-color: ${(p) => "#fff"}; or any hex color you need

**Comment by renzified** [comment]
You received that error because you did not supplied backgroundColor for the tabStyle. It should be like this
```
<Tab.Navigator
                tabBarOptions={
                    {
                        activeTintColor: 'white',
                        inactiveTintColor: 'grey',
                        activeBackgroundColor: 'purple',
                        labelStyle: {
                            fontFamily: 'Montserrat-Bold',
                            color: 'white'
                        },
                        tabStyle:{
                            backgroundColor: 'white' //Please insert this in your code
                        }
                    }
                }
>
...
```

**Comment by torgeadelin** [comment]
This is gonna be fixed in the next version. 
All configuration will be optional and default to a set design.
