### ISSUE TITLE
How to hide bottom bar for child screens?

### ISSUE THREAD

**Issue by aravind123cs** [torgeadelin/react-native-animated-nav-tab-bar#36]

**Comment by sujinjuly4** [comment]
@torgeadelin Can you please find a solution ?
`tabBarVisible` is not working.

**Comment by torgeadelin** [comment]
Could you post a screenshot illustrating the issue? Thanks!

**Comment by aravind123cs** [comment]
![child screen](https://user-images.githubusercontent.com/29692028/91124325-aeda3e80-e6bc-11ea-991b-7c2ee5caadf9.png)
![parent screen](https://user-images.githubusercontent.com/29692028/91124338-b3065c00-e6bc-11ea-8164-b15098cfbfd1.png)
is there any property to hide bottom bar for child screens

**Comment by torgeadelin** [comment]
Oh, I see. I will look into it today.

**Comment by ahmetozalp** [comment]
Could you solve this problem? I want to hide it on some screens

**Comment by ahmetozalp** [comment]
fixed problem.

Removed module 🙃

**Comment by torgeadelin** [comment]
A quick google search shows that you should't use `tabBarVisible` prop anymore.
Let me know if this new technique (https://reactnavigation.org/docs/hiding-tabbar-in-screens/#!) fixes your issue. I just tested and seems to work.
