### ISSUE TITLE
Screen reloads on every focus

### ISSUE THREAD

**Issue by Ravi448** [torgeadelin/react-native-animated-nav-tab-bar#37]
### What is expected
The screen should call `componentDidMount` only on first focus.

### What is current behaviour
Is there any way to prevent screen refresh on tab focus? I have added some api calls on `componentDidMount` and this is being called on every focus.

**Comment by MukhametzhanDev** [comment]
+++

**Comment by mstf0ta-app** [comment]
same here i tried to add lazy option but without any effect

**Comment by torgeadelin** [comment]
Sorry, this is currently being fixedd.

**Comment by torgeadelin** [comment]
Fixed.
