### ISSUE TITLE
Open modal

### ISSUE THREAD

**Issue by kasper-madsen** [torgeadelin/react-native-animated-nav-tab-bar#38]
Hi, this is an awsome component. would it be possible to extend the tab screens to be configured like react native navigation tabbar?

either provide away to do
         options={{
           tabBarButton: (props) => (
             <TouchableOpacity
               {...props}
               onPress={() => navigation.navigate('ModalView')}
             />
           ),
        }}

Or 

listeners={({navigation, route}) => ({
          tabPress: (e) => {
            // Prevent default action
            e.preventDefault();

            // Do something with the `navigation` object
            navigation.navigate('ModalView');
          },
        })}

**Comment by torgeadelin** [comment]
Fixed. in 3.0.4
You can use as follows:
```
listeners={{
  tabPress: e => {
  // Prevent default action
  e.preventDefault()
  console.log('ss')
  },
}}
```
