### ISSUE TITLE
Question: Does it support badge? 

### ISSUE THREAD

**Issue by kristoff2016** [torgeadelin/react-native-animated-nav-tab-bar#39]
Hello, 
Thank you for nice plugin for us. I really appreciate it.  is it possible to support badge? 

Thanks

**Comment by kristoff2016** [comment]
I tried to add an option follow https://reactnavigation.org/docs/tab-based-navigation but it does not show

**Comment by cgarcia55** [comment]
try adding the badge directly to the icon like this:
`<Tabs.Screen
        name="Cart"
        component={Cart}
        options={{
          tabBarIcon: ({ focused, color }) => (
            <View>
              <TabBarIcon
                focused={focused}
                tintColor={color}
                name="shopping-cart"
              />
              <Badge
                value="1"
                status="error"
                containerStyle={{ position: "absolute", top: -12, right: -12 }}
              />
            </View>
          ),
        }}
      />`

**Comment by kristoff2016** [comment]
Thank you @cgarcia55 so we can use the only custom something like this?

**Comment by torgeadelin** [comment]
Hi, thanks for the kind words.
Actually @cgarcia55's suggestion is great. This way you have full power to customise it however you like. The badge option inside the navigator is the default style for the OS.

**Comment by torgeadelin** [comment]
I'm going to close this issue now, since there's a workaround. If there's really need of the default one I'm waiting for more people to ask for it.

**Comment by kristoff2016** [comment]
Hi @torgeadelin, it would be great if we can use it from default and customize.

**Comment by fukemy** [comment]
lol the badge position changed when tab selected and unselected, funny
