### ISSUE TITLE
Still rerendering problem.

### ISSUE THREAD

**Issue by cgarcia55** [torgeadelin/react-native-animated-nav-tab-bar#41]
i'm still facing the issue with the re-rendering problem, there is a configuration or props that im missing?
Every tab change, the active tab re-render, so when i go back, re-render as well

**Comment by torgeadelin** [comment]
Did you update to 3.0.4?

**Comment by cgarcia55** [comment]
`"react-native-animated-nav-tab-bar": "^3.0.4",`, yes, yes that's the weird thing

**Comment by kristoff2016** [comment]
Hi, what is the issue with re-rendering?

**Comment by cgarcia55** [comment]
every change of tabs, re-render the active tab. If navigate from home to cart and then go back to home, i have to wait Home finish de render.

**Comment by torgeadelin** [comment]
I'll have a look today. It's weird because I pushed a fix on Sunday 🤔

**Comment by torgeadelin** [comment]
I just tested again, and it seems to work for me. I'm testing on iOS 14, with React native 0.63.
Please delete your `node_modules` and run the local server with `react-native start --reset-cache`.
The component is initialised only once.

Try to run the example project from the repo and see if it works there. Add a component did mount to one of the screens and check.

**Comment by cgarcia55** [comment]
THANKS!! it was that. Now works great!
