### ISSUE TITLE
Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'?

### ISSUE THREAD

**Issue by Duya3fithou** [torgeadelin/react-native-animated-nav-tab-bar#42]
I use TypeScript, and install follow your docs.
My import: 

![Screen Shot 2020-09-29 at 10 53 22 AM](https://user-images.githubusercontent.com/44860282/94510867-0c285900-0242-11eb-82be-8827935b3ecd.png)

My Tab.Navigator:

![Screen Shot 2020-09-29 at 11 03 57 AM](https://user-images.githubusercontent.com/44860282/94511426-7ee60400-0243-11eb-9527-b8f7b56fcc9f.png)

After, i wrapp it, and pass to 2 stack is AuthStack and AppStack to check user loggin.

![Screen Shot 2020-09-29 at 11 04 52 AM](https://user-images.githubusercontent.com/44860282/94511469-9f15c300-0243-11eb-9e51-db6ce49d044a.png)

  In App.tsx, my return:
![Screen Shot 2020-09-29 at 11 05 31 AM](https://user-images.githubusercontent.com/44860282/94511506-bf458200-0243-11eb-87f4-94414cc398f1.png)

-> However, it through error: Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'?
But I wrapper it in  App.tsx, How to solve this problem ? 
 "react-native": "0.63.2",
 "react-native-animated-nav-tab-bar": "^3.0.4",
 "@react-navigation/native": "^5.1.4",
Tks your pretty lib.

**Comment by torgeadelin** [comment]
I think it's due to the fact that you AppStack is wrapped in `Host`?

**Comment by torgeadelin** [comment]
I just replicated you code and it seems to work for me. I think it has nothing to do with this package. Does it work if you replace Tabs with `createBottomTabNavigator()` instead of Animated..etc?

**Comment by Duya3fithou** [comment]
if I used createBottomTabNavigator(), it work normally
And I try remove Host but it still not working

**Comment by torgeadelin** [comment]
Could you post more details about your project? Source code for the affected parts? Also include the whole error log. If I can't reproduce I can't really fix it :(

**Comment by Duya3fithou** [comment]
yep. 
I used base project from https://github.com/cuongnm2301/demo-app
and just change content of file RootSences.tsx to: [Link file](https://pastebin.com/QzEdGrqr)
Here is my problem

![Simulator Screen Shot - iPhone X - 2020-09-30 at 14 41 00](https://user-images.githubusercontent.com/44860282/94656977-00649180-032b-11eb-8e03-f3c84178f8d0.png)

**Comment by Duya3fithou** [comment]
tks you very much becase your quick reply.

**Comment by torgeadelin** [comment]
No worries! Thanks for the details. I'll have a look once I finish work today:)

**Comment by torgeadelin** [comment]
Sorry, could you try to share the entire error trace call stack and not just a screenshot? or some logs

**Comment by torgeadelin** [comment]
Ok, i just cloned the demo app, i installed the package, copy pasted the code you provided in RootScenes and it works. Try to run the app with react-native start --reset-cache, but before that delete the node_modules and install everything again.

**Comment by Duya3fithou** [comment]
I remove node_modules and reinstall. run react-native start --reset-cache. and it work perfect. tks your lib and support.

**Comment by ferostar** [comment]
Hi!

I'm having the same issue. Reinstalled `node_modules`, ran `react-native start --reset-cache` and it still happens.

```
"react-native": "0.63.2",
"@react-navigation/native": "^5.7.3",
"@react-navigation/stack": "^5.9.0",
"react-native-animated-nav-tab-bar": "^3.0.4",
```

Code setup is pretty much the same as @Duya3fithou , only using JS.

```
return (
    <>
      <AppearanceProvider>
        <StatusBar 
          barStyle={barStyle}
          backgroundColor={colors.header} 
          />
        <SafeAreaProvider>
        <Provider store={store}>
          <SomeStuffContainer>
            <NavigationComesHere />
          </SomeStuffContainer>
        </Provider>
        </SafeAreaProvider>
      </AppearanceProvider>
    </>
  )
```

Tried removing the other Providers and Containers above but nothing changes. And Navigation code here is similar, a `NavigationContainer`, a `RootStack` and different stacks depending on user state.

```
return (
      <NavigationContainer>
        {<RootStack.Navigator mode='modal'>
          { (hazUser) ? this.renderNonAuth() : this.renderAuth() }
        </RootStack.Navigator>}
      </NavigationContainer>
    )

const TabStack = AnimatedTabBarNavigator()

function TabNavigator() {
  return (
    <TabStack.Navigator>
      <TabStack.Screen name='First' component={FirstNavigator} />
      <TabStack.Screen name='Second' component={SecondNavigator} />
    </TabStack.Navigator>
  );
}
```

Any idea? Would love to use your library.

**Comment by algokano** [comment]
same issue
"react-native": "0.63.2",
    "react-native-animated-nav-tab-bar": "^3.0.4",
"@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2"

**Comment by timothylui** [comment]
I'm also getting the same issue. If it makes any difference I'm using classes for my components rather than functions.

    "react-native": "0.63.3",
    "react-native-animated-nav-tab-bar": "^3.0.4",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.6.2",

**Comment by algokano** [comment]
[animated-tabbar](https://www.npmjs.com/package/@gorhom/animated-tabbar) worked great for me

**Comment by torgeadelin** [comment]
@Sarvarr , @timothylui I'm afraid I can't reproduce the issue. It works fine for me on iOS
```
"@react-navigation/bottom-tabs": "^5.2.7",
"@react-navigation/native": "^5.7.6",
"@react-navigation/stack": "^5.9.3",
"react": "^16.13.1",
"react-native": "0.63.2",
```

I also tried with class component.
