### ISSUE TITLE
Bottom bar overlays content of ScrollView

### ISSUE THREAD

**Issue by aeife** [torgeadelin/react-native-animated-nav-tab-bar#43]
I started with the expo tab example which is a pretty simple project using a bottom tab bar. I exchanged the bottom tab bar with the animated tab bar component. I noticed that the animated bottom tab bar overlays the content of a ScrollView. In comparison using the default bottom tab bar the ScrollView is above the header so everything can be scrolled into the view.

Do I need to configure something or is this different behavior to the default bar intended? I'm not using the floating variant.

**Comment by torgeadelin** [comment]
Hi, I was hoping this wont be an issue. I will patch a fix for this so that when the navbar is not floating, it will take the space below the screen and not on top of it. I'll try to work on this over the weekend.

**Comment by Relax594** [comment]
Same issue here, would be awesome to have this one fixed

**Comment by algokano** [comment]
Same issue

**Comment by torgeadelin** [comment]
Fixed #48, Please upgrade to 3.0.5
