### ISSUE TITLE
 Possible to use gardient color for 'activeBackgroundColor' props?

### ISSUE THREAD

**Issue by Duya3fithou** [torgeadelin/react-native-animated-nav-tab-bar#44]
![Component 13 – 2@3x](https://user-images.githubusercontent.com/44860282/94762342-98b55180-03d1-11eb-8d20-3cf7af5f9c44.png)
How do like this? 
Is it feasible to use gardient color? 
And how to set width for activeBackgroundColor?
Many tks for pretty lib.

**Comment by amarjitsingh65** [comment]
Hi, am not able to create a floating tab with less rounding corners. how you rounder the corner with less radius as in the above screen. I have a default radius which is too large.
<img width="318" alt="floating-bottom-bar" src="https://user-images.githubusercontent.com/34943963/95498775-2dcbc380-0959-11eb-9858-fb0f899da5a4.png">

**Comment by torgeadelin** [comment]
Hi, I will try to add support for gradients as well in the near future :)

**Comment by NISUSIN** [comment]
Hello, for those who want to add a gradient using the ([LinearGradient library](https://github.com/react-native-linear-gradient/react-native-linear-gradient)) here's the workaround, edit this file 

> react-native-animated-nav-tab-bar/dist/lib/index.js (line 471)

Update this : 
`React__default["default"].createElement(Dot, { dotCornerRadius: dotCornerRadius, topPadding: topPadding, activeTabBackground: activeTabBackground, style: reactNative.I18nManager.isRTL
                        ? {
                            right: animatedPos.interpolate({
                                inputRange: [0, 1],
                                outputRange: [prevPos, pos],
                            }),
                        }
                        : {
                            left: animatedPos.interpolate({
                                inputRange: [0, 1],
                                outputRange: [prevPos, pos],
                            }),
                        }, width: width, height: height })`

to this code : 
`React__default["default"].createElement(Dot, { dotCornerRadius: dotCornerRadius, topPadding: topPadding, activeTabBackground: activeTabBackground, style: reactNative.I18nManager.isRTL
                        ? {
                            right: animatedPos.interpolate({
                                inputRange: [0, 1],
                                outputRange: [prevPos, pos],
                            }),
                        }
                        : {
                            left: animatedPos.interpolate({
                                inputRange: [0, 1],
                                outputRange: [prevPos, pos],
                            }),
                        }, width: width, height: height }, React__default["default"].createElement(LinearGradient, {colors: ["#EBA767", "#FF5151"], start: { x: 0, y: 0 }, end: { x: 1, y: 0 }, style:{flex: 1, borderRadius: dotCornerRadius}}))`

Don't forget to add `import LinearGradient from 'react-native-linear-gradient';` at the beginning of the file
