### ISSUE TITLE
Feature Request: use horizontal swiping feature of createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by Relax594** [torgeadelin/react-native-animated-nav-tab-bar#46]
Is there way to use this together with the swiping feature of [createMaterialTopTabNavigator](https://reactnavigation.org/docs/material-top-tab-navigator/)?

By using it like this it behaves the same as [createBottomTabNavigator](https://reactnavigation.org/docs/bottom-tab-navigator), which i guess is what you use:
```
<Tab.Navigator
      tabBarPosition="bottom"
      lazy={true}>
{...}
</Tab.Navigator>
```

I think this would be awesome paired with the animations you already provide here.

**Comment by torgeadelin** [comment]
Hi, I'm afraid not. At least at the moment, I'm not planning to extend it to the material top nav. But if you feel up for the task (and can dedicate the time for it) I'd be more than happy to welcome contributions.
