### ISSUE TITLE
useScrollToTop doesnt work

### ISSUE THREAD

**Issue by algokano** [torgeadelin/react-native-animated-nav-tab-bar#47]
if I used createBottomTabNavigator(), [useScrollToTop](https://reactnavigation.org/docs/use-scroll-to-top) work normally
"react-native": "0.63.2",
    "react-native-animated-nav-tab-bar": "^3.0.4",
"@react-native-community/masked-view": "^0.1.9",
    "@react-navigation/bottom-tabs": "^5.2.7",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.11",

**Comment by torgeadelin** [comment]
Fixed #48 . Upgrade to 3.0.5
