### ISSUE TITLE
How can i customize TabButton style

### ISSUE THREAD

**Issue by caglardurmus** [torgeadelin/react-native-animated-nav-tab-bar#51]
I want to disable flex:1 option on TabButton style. 
I don't want them with same witdh.
Is that possible?

**Comment by torgeadelin** [comment]
Hi,

At the moment that's not possible because it would break the animation. I'll try to find a way to have both the ability to set specific width for each tab button and to have the animation working.

**Comment by caglardurmus** [comment]
I deleted flex: 1 option and it works fine.

**Comment by torgeadelin** [comment]
Well that one is interesting, do you reckon adding a prop to customise the tab button itself would help you? Similar to tabStyle?

**Comment by caglardurmus** [comment]
i just forked your repo and deleted flex: 1 from TabButton.

**Comment by caglardurmus** [comment]
I add responsive property to appearence. You can check my commits

https://github.com/caglardurmus/react-native-animated-nav-tab-bar/commits
