### ISSUE TITLE
how to change the font family of the tab bar?

### ISSUE THREAD

**Issue by Saff-Elli-Khan** [torgeadelin/react-native-animated-nav-tab-bar#52]
Hi Torgeadelin,
I'm unable to change the font family of the tab bar can you please add a style prop or add an option to change the font family or guide me on how to change the font family? I will be very thankful to you 👍

**Comment by Saff-Elli-Khan** [comment]
I have fixed the issue on my own. If anybody needs this feature then follow these steps:
1. Goto your npm modules in react-native-animated-nav-tab-bar
2. Open AnimatedTabBarNavigator.js
3. find this object labelStyle and then add another style name fontFamily and give it a default value "system font" and done :)
4. Now goto your code and add labelStyle object inside tabBarOptions and use your own fonts.
Cheers

**Comment by hbendix** [comment]
^ This is not an acceptable workaround as node modules are auto-generated.

**Comment by hbendix** [comment]
You can change the label font family by using `labelStyle` and assigning `fontFamily`
