### ISSUE TITLE
Add badge to icon bottom tabbar

### ISSUE THREAD

**Issue by Duya3fithou** [torgeadelin/react-native-animated-nav-tab-bar#54]
Hmmm. 
Is there any way to add badge to bottom tab icon. tks you.
I can custom when focus tab. But it not focused, I can't
![Screen Shot 2020-10-23 at 2 12 28 PM](https://user-images.githubusercontent.com/44860282/96967726-23552080-153a-11eb-93e7-1e5a09bf5870.png)

**Comment by OnurSevket** [comment]
I think,This is very important

**Comment by ciocan** [comment]
You can use hack like this: enclose the icon with an external view wrapper positioned relative and add another absolute view with a text styled as the badge.

Example code:

```
      <Tab.Screen
        name="Profile"
        component={ProfileScreen}
        listeners={{ tabPress: handleTabPress }}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Div position="relative">
              {!!badgeCount && (
                <Div
                  bg="red"
                  position="absolute"
                  right={-10}
                  top={-10}
                  w={16}
                  h={16}
                  rounded={16}
                  zIndex={1}
                  justifyContent="center"
                >
                  <Text fontSize="xs" color="white" textAlign="center">
                    {badgeCount}
                  </Text>
                </Div>
              )}
              <Icon
                name="account-circle"
                color={color}
                fontSize={size}
                fontFamily="MaterialIcons"
              />
            </Div>
          ),
        }}
      />
```
(it uses react-native-magnus as the utility UI library, so you can replace the Div with a react native View)

**Comment by Duya3fithou** [comment]
Tks @ciocan for your suggest. And I solved this. And my solution same you, xD

**Comment by Siddharth2212** [comment]
You can solve  this by using BadgedIcon from react native elements
