### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by zeeshanmazhar** [torgeadelin/react-native-animated-nav-tab-bar#55]
I am getting error while making the tab bar and i don't understand how to remove it.
![image](https://user-images.githubusercontent.com/6506972/97199506-e4d99300-17d1-11eb-9774-40d1bf385429.png)

**Comment by torgeadelin** [comment]
Closing for not providing enough details...
If you're still experiencing the issue, please provide how to reproduce it and some logs.
