### ISSUE TITLE
React Navigation v4

### ISSUE THREAD

**Issue by butri71** [torgeadelin/react-native-animated-nav-tab-bar#56]
Is it compatible?

**Comment by buremer** [comment]
Nope. As said in the readme/documentation:
```
In order to use the component, you need to have React Navigation v5 installed.
```

A guide to upgrade your own navigation to V5 can be found here:
https://reactnavigation.org/docs/upgrading-from-4.x/

**Comment by butri71** [comment]
Ok I've just migrated to V5 and installed it. Looking good so far ...

Thanks
