### ISSUE TITLE
keyboardHidesTabBar not working

### ISSUE THREAD

**Issue by danieldeev** [torgeadelin/react-native-animated-nav-tab-bar#57]
In the **tabBarOptions** settings on **keyboardHidesTabBar**, when trying to set **"keyboardHidesTabBar": true** to hide the tabs when opening the keyboard, even if set to "true", the lib does not hide the tabs and when using the original React Navigation Tabs lib it works. Can someone help me?

**Comment by ranuwp** [comment]
@danieldeev how to solve it?

**Comment by danieldeev** [comment]
> @danieldeev how to solve it?

I couldn't solve it, I'm using redux to close the keyboard when it is triggered

**Comment by fukemy** [comment]
any new?
