### ISSUE TITLE
keyboardHidesTabBar doesn't work

### ISSUE THREAD

**Issue by ranuwp** [torgeadelin/react-native-animated-nav-tab-bar#63]
Whenever the keyboard appears, the tab bar will still there and hides the input for keyboard

**Comment by torgeadelin** [comment]
Does this happen on ios or android?
If it is an actual issue, it's most likely due to react-navigation.

**Comment by papidb** [comment]
Hey, it happens on android, not ios. Tried passing in keyboardHidesTabBar: true into tabBarOptions but it doesn't work. Is there a fix for this?

**Comment by m-ruhl** [comment]
@torgeadelin 

I can confirm the issue. When I use "@react-navigation/bottom-tabs" the tabbar is hidden.
When using this framework it looks like this
![bottomBar](https://user-images.githubusercontent.com/867772/115894627-c5a68000-a459-11eb-8ed2-7b9040fd0964.png)

**Comment by papidb** [comment]
So I was able to come up with a very buggy fix. https://github.com/benjamin-daniel/react-native-animated-nav-tab-bar/tree/bug/keyboardHidesOnTab will still take a look at it. I heavily copied https://github.com/react-navigation/react-navigation/tree/main/packages/native. Check it out if you are free! @m-ruhl @torgeadelin

**Comment by hillkim** [comment]
@papidb Why cant you create a PR for this? Can I do it?

**Comment by papidb** [comment]
Yeah, you can. I don't mind, but like I said it is very rough, you can try to tidy it up. Thanks.

**Comment by mahmoudshaeerhomzmart** [comment]
++
