### ISSUE TITLE
Warning From Icon and TabBar component

### ISSUE THREAD

**Issue by Tanvir-rahman** [torgeadelin/react-native-animated-nav-tab-bar#7]
I am getting following warnings while using Icon with TabBar component
![Screenshot 2019-11-09 at 8 56 29 AM](https://user-images.githubusercontent.com/15964566/68521805-dba89b00-02ce-11ea-957c-351cbde9c726.png)
![Screenshot 2019-11-09 at 8 56 13 AM](https://user-images.githubusercontent.com/15964566/68521806-dea38b80-02ce-11ea-8c56-1d584d82e28a.png)

Here's associated ways i tried-
NavigationOptions - 
```
    Settings: {
      screen: SettingsNavigator,
      navigationOptions: {
        tabBarIcon: ({ focused, tintColor }) => (
          <TabBarIcon focused={focused} tintColor={tintColor} name="menu" />
        ),
        tabBarLabel: "More",
      },
    }
```
Tab Bar component - 
```
const TabBarIcon = (props) => {
  return (
    <Icon
      name={props.name}
      size={props.size ? props.size : 16}
      color={props.focused ? props.tintColor : "#222222"}
    />
  );
};
```

Tab Bar options and Component - 
```
  {
    tabBarOptions: {
      activeTintColor: "#2E98FF",
      inactiveTintColor: "#222222"
    },
    tabBarComponent: props => (
      <TabBar
        activeColors={"#FFFFFF"}
        activeTabBackgrounds={"#2E98FF"}
        {...props}
      />
    ),
  },
```

Any way to fix this?

**Comment by torgeadelin** [comment]
Hi @Tanvir-rahman !
I think you're using Expo for the web.  I haven't tested the package with that. It should work fine if used without expo. I'll try to see if I can fix it and let you know. 

It would be helpful to get all your code and all details about your app as the answer I gave above is based only on assumptions.

Tanks!

**Comment by Tanvir-rahman** [comment]
Yes i have tried Expo for the web and got following warnings.

**Comment by torgeadelin** [comment]
Closed due to no further information.
