### ISSUE TITLE
'have your wrapper your NavigationContainer' Bug

### ISSUE THREAD

**Issue by DSPerera95** [torgeadelin/react-native-animated-nav-tab-bar#70]
'have your wrapper your NavigationContainer' bug still appears to be there even after updating @react-navigation/stack 5.13.0, @react-navigation/native 5.9.0 and @react-navigation/bottom-tabs 5.11.3

**Comment by torgeadelin** [comment]
Did you also update the package to 3.1.1?

**Comment by DSPerera95** [comment]
@torgeadelin yes I did. its updated to 3.1.1

**Comment by torgeadelin** [comment]
Please provide how you're using the component and proper logs. Thanks.

Did you try to reset cache when running npm run start?

**Comment by DSPerera95** [comment]
reset the cache and it works now. thanks!
