### ISSUE TITLE
Possible to hide a specific tab?

### ISSUE THREAD

**Issue by macist-m** [torgeadelin/react-native-animated-nav-tab-bar#74]
Hello, with regular tab navigation, it is possible to hide a specific tab form the bar with this...

```
<Tab.Navigator
      screenOptions={({ route }) => ({
        tabBarButton: [
          "Route1ToExclude",
          "Route2ToExclude"
        ].includes(route.name)
          ? () => {
              return null;
            }
          : undefined,
      })}
    >
```

Yet this is not working with react-native-animated-nav-tab-bar...

İs it possible to hide a tab with stack navigation nested in?

**Comment by emilstepanian** [comment]
I have not tried specifically this, but I am currently struggling with other configuration options in screenOptions prop. 

Nothing works with screenOptions in Tab.Navigator.

**Comment by namachan0219** [comment]
@macist-m 

I hope my hack is helpful.

In the stack navigator nested in the bottom navigator
Nested in the bottom navigator, the stack navigator controls whether it is shown or hidden.

`  
import React, { useLayoutEffect } from "react";
import { getFocusedRouteNameFromRoute } from "@react-navigation/native";
const navName: any = getFocusedRouteNameFromRoute(route);

useLayoutEffect(() => {
    switch (navName) {
      case "Name of the stack you want to hide please":
        navigation.setOptions({ tabBarVisible: false });
        break;

      default:
        navigation.setOptions({ tabBarVisible: true });
        break;
    }

    return;
  }, [navigation, route]);
`

**Comment by namachan0219** [comment]
@macist-m 
I hope you find my hack helpful!
Bottom Implement it in the Stack Navigator nested in the Navigator.

```
// add your stack navigator 
import React, { useLayoutEffect } from "react";
import { getFocusedRouteNameFromRoute } from "@react-navigation/native";

const navName: any = getFocusedRouteNameFromRoute(route);

useLayoutEffect(() => {
switch (navName) {
case "The stack screen name you want to hide.....":
navigation.setOptions({ tabBarVisible: false });
break;

  default:
    navigation.setOptions({ tabBarVisible: true });
    break;
}
return;
}, [navigation, route]);
```
