### ISSUE TITLE
Gettting black line on top of tab-bar

### ISSUE THREAD

**Issue by Lekhrajk** [torgeadelin/react-native-animated-nav-tab-bar#75]
I am getting unwanted black line on top of tab-bar  any solution ?
![WhatsApp Image 2021-02-18 at 15 18 25](https://user-images.githubusercontent.com/42565741/108338860-bc502b80-71fc-11eb-8374-ced70430d0e8.jpeg)

**Comment by torgeadelin** [comment]
Could you post some reproducible code, please?
