### ISSUE TITLE
Safe-Area on iPhone 12 Pro (Max)

### ISSUE THREAD

**Issue by m-ruhl** [torgeadelin/react-native-animated-nav-tab-bar#76]
Hey 👋 ,

on the iPhone 12 Pro and iPhone 12 Pro Max the safe area is not displayed correctly as seen in the screenshot:
![safe_area](https://user-images.githubusercontent.com/867772/108351959-79835900-71e6-11eb-9850-28ce2ee33ebf.png)

**Comment by torgeadelin** [comment]
fixed, please update to 3.1.3
