### ISSUE TITLE
Backbutton from navigation back, wrong position in the tabbar

### ISSUE THREAD

**Issue by IronTony** [torgeadelin/react-native-animated-nav-tab-bar#8]
Hi,

woah component 😄 
Everything is fine in iOS and Android if you use the tabbar navigation (testing with react-navigation v4), but if I use a button that goBack from Tab2 to Tab1 I see this:
![image](https://user-images.githubusercontent.com/3645225/68951505-8123a900-07be-11ea-9c4c-660380e7b72d.png)

I am trying to fix it, but if you are faster then me I need some help 😸 

Thx

**Comment by torgeadelin** [comment]
Hi!
Thanks for the feedback! 😇

Please update the component, we fixed that issue from 1.03 to 1.04. Let me know if the issue still persists.

Thanks!

**Comment by IronTony** [comment]
wow, super fast!
I am using the 1.0.4 😉 
If you need more info or see the problem live, just tell me

**Comment by torgeadelin** [comment]
Are you having the issue when you press the physical back button on the device or when you use `this.props.navigate(“Screen x”)`?

**Comment by IronTony** [comment]
When I click on a button that do `navigation.navigate("Screen X")`

**Comment by IronTony** [comment]
the problem is the style of the `<Dot />` component, that doesn't move correctly

**Comment by torgeadelin** [comment]
I see. Not it makes sense. The reason is because the animation is not fired on the `navigate`. This is the same issue as #3. I didn’t have time to look into it yet, maybe you can check my response here #3 and try to fix it. I’m super busy this weekend but I’ll try something next week. 

I’m sorry for the inconvenience.

**Comment by IronTony** [comment]
fine thx. Hope to come back with good news and do a PR to you. Thank you again

**Comment by torgeadelin** [comment]
Closed due to duplication, see #3

**Comment by saraf22** [comment]
adding this in Tabbar.js does the fix @torgeadelin

componentDidUpdate(prevProps) {
if(prevProps.navigation.state.index !== this.props.navigation.state.index) {
    this.animation(this.state.animatedPos).start(() => {
        this.setState({
          prevPos: this.state.pos,
        });
        this.state.animatedPos.setValue(0);
      });
}
}
